
#define BASLER_ACE_SAFEMODE true

#define IDC_BASLER_MIN_SLIDER_MIN_EDIT 1040
#define IDC_BASLER_MIN_SLIDER_MAX_EDIT 1043
#define IDC_CAMERA_MODE_COMBO 1004
#define IDC_EXPOSURE_MODE_COMBO 1007
#define IDC_REPETITIONS_EDIT 1003
#define IDC_ARM_BASLER_BUTTON 1000
#define IDC_DISARM_BASLER_BUTTON 1001
#define IDC_TRIGGER_MODE_COMBO 1021
// the basler has a 10 bit dac.
#define PICTURE_PALETTE_SIZE 256


